import {getStore} from '@netlify/blobs';
import webpush from 'web-push';
import type {Config} from '@netlify/functions';
import type {PushRecord} from './_shared/push';
export const config:Config={schedule:'*/15 * * * *'};
const texts=['Ada beberapa menit untuk bermain bersama Si Kecil hari ini? ❤️','Ide stimulasi hari ini sudah siap.','Tidak perlu aktivitas panjang. Mau coba satu permainan sederhana?','Momen kecil bersama Si Kecil bisa dimulai dari beberapa menit bermain.'];
export default async function(){const pub=process.env.VAPID_PUBLIC_KEY,priv=process.env.VAPID_PRIVATE_KEY,subject=process.env.VAPID_SUBJECT;if(!pub||!priv||!subject)return new Response('VAPID not configured',{status:503});webpush.setVapidDetails(subject,pub,priv);const storage=getStore({name:'lsk-push-subscriptions',consistency:'strong'});const now=new Date();let sent=0;for await(const page of storage.list({prefix:'subscription:',paginate:true})){for(const item of page.blobs){const rec=await storage.get(item.key,{type:'json'}) as PushRecord|null;if(!rec?.enabled||rec.snoozedUntil&&Date.parse(rec.snoozedUntil)>now.getTime())continue;try{const local=new Intl.DateTimeFormat('en-US',{timeZone:rec.timezone,weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const val=(type:string)=>local.find(x=>x.type===type)?.value??'';const day=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(val('weekday'));const minutes=Number(val('hour'))*60+Number(val('minute'));const [h,m]=rec.preferredTime.split(':').map(Number);if(!rec.days.includes(day)||minutes<h*60+m||minutes>=h*60+m+15)continue;const slot=`${val('year')}-${val('month')}-${val('day')}:${rec.preferredTime}`;if(rec.lastSentSlot===slot)continue;
 // Claim the slot before delivery to prevent duplicate sends on overlapping scheduled runs.
 const fresh=await storage.getWithMetadata(item.key,{type:'json'});if(!fresh?.etag||fresh.data.lastSentSlot===slot)continue;const claimed=await storage.setJSON(item.key,{...fresh.data,lastSentSlot:slot,updatedAt:now.toISOString()},{onlyIfMatch:fresh.etag});if(!claimed.modified)continue;
 await webpush.sendNotification({endpoint:rec.endpoint,keys:{p256dh:rec.p256dh,auth:rec.auth}},JSON.stringify({title:'Langkah Si Kecil',body:texts[Math.abs([...slot].reduce((a,c)=>a+c.charCodeAt(0),0))%texts.length],url:'/hari-ini'}),{TTL:3600});sent++;
 }catch(err){const status=(err as {statusCode?:number}).statusCode;if(status===404||status===410)await storage.delete(item.key).catch(()=>{});}}
 }return new Response(JSON.stringify({sent}),{headers:{'content-type':'application/json'}})}
