import {getSettings,saveSettings} from './db';
function hex(bytes:Uint8Array){return [...bytes].map(n=>n.toString(16).padStart(2,'0')).join('')}
function applicationServerKey(base64:string){const s=(base64+'='.repeat((4-base64.length%4)%4)).replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
export const pushSupported=()=>typeof window!=='undefined'&&isSecureContext&&'Notification'in window&&'serviceWorker'in navigator&&'PushManager'in window;
export const pushConfigured=()=>Boolean(import.meta.env.VITE_VAPID_PUBLIC_KEY);
async function identity(){let s=await getSettings();if(!s.installationId||!s.pushManageSecret){if(!globalThis.crypto?.randomUUID||!globalThis.crypto.getRandomValues)throw Error('Perangkat ini tidak menyediakan identitas aman untuk pengingat.');const bytes=crypto.getRandomValues(new Uint8Array(32));s=await saveSettings({installationId:crypto.randomUUID(),pushManageSecret:hex(bytes)})}return s}
const timezone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Jakarta';
export async function enablePush(time:string,days:number[]){if(!pushSupported())throw Error('Pengingat push belum didukung di perangkat ini.');const publicKey=import.meta.env.VITE_VAPID_PUBLIC_KEY;if(!publicKey)throw Error('Pengingat push belum dikonfigurasi pada situs ini.');const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Izin notifikasi belum diberikan.');const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:applicationServerKey(publicKey)});const s=await identity();const res=await fetch('/.netlify/functions/push-subscribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({installationId:s.installationId,managementSecret:s.pushManageSecret,subscription:subscription.toJSON(),timezone:timezone(),preferredTime:time,days})});if(!res.ok)throw Error('Server pengingat belum tersedia. Coba lagi nanti.');await saveSettings({notificationEnabled:true,reminderTime:time,reminderDays:days});}
export async function updatePush(time:string,days:number[],enabled:boolean,snoozedUntil?:string){const s=await identity();const res=await fetch('/.netlify/functions/push-settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({installationId:s.installationId,managementSecret:s.pushManageSecret,timezone:timezone(),preferredTime:time,days,enabled,snoozedUntil})});if(!res.ok)throw Error('Pengaturan pengingat belum tersimpan di server.');return saveSettings({notificationEnabled:enabled,reminderTime:time,reminderDays:days,reminderSnoozedUntil:snoozedUntil})}
export async function disablePush(){const s=await getSettings();if(s.installationId&&s.pushManageSecret){const res=await fetch('/.netlify/functions/push-unsubscribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({installationId:s.installationId,managementSecret:s.pushManageSecret})});if(!res.ok)throw Error('Pengingat belum berhasil dimatikan di server.')}const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();await sub?.unsubscribe();await saveSettings({notificationEnabled:false});}
const weekDays=['SU','MO','TU','WE','TH','FR','SA'];
export function makeCalendarEvent(time:string,days:number[],now=new Date()){
  const [hours,minutes]=time.split(':').map(Number);
  const selected=[...new Set(days)].filter(day=>Number.isInteger(day)&&day>=0&&day<=6).sort();
  if(!selected.length||!Number.isInteger(hours)||hours<0||hours>23||!Number.isInteger(minutes)||minutes<0||minutes>59)throw Error('Pilih jam dan setidaknya satu hari pengingat.');
  const start=new Date(now);
  start.setHours(hours,minutes,0,0);
  while(start<=now||!selected.includes(start.getDay()))start.setDate(start.getDate()+1);
  const end=new Date(start);
  end.setMinutes(end.getMinutes()+10);
  const local=(date:Date)=>`${date.getFullYear()}${String(date.getMonth()+1).padStart(2,'0')}${String(date.getDate()).padStart(2,'0')}T${String(date.getHours()).padStart(2,'0')}${String(date.getMinutes()).padStart(2,'0')}${String(date.getSeconds()).padStart(2,'0')}`;
  const stamp=(date:Date)=>date.toISOString().replace(/[-:]/g,'').split('.')[0]+'Z';
  return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Langkah Si Kecil//Pengingat//ID','BEGIN:VEVENT',`UID:lsk-${local(start)}-${selected.join('')}@langkahsikecil`,`DTSTAMP:${stamp(now)}`,`DTSTART:${local(start)}`,`DTEND:${local(end)}`,`RRULE:FREQ=WEEKLY;BYDAY=${selected.map(day=>weekDays[day]).join(',')}`,'SUMMARY:Waktu bermain bersama Si Kecil','END:VEVENT','END:VCALENDAR',''].join('\r\n');
}
export function calendarReminder(time:string,days:number[]){const body=makeCalendarEvent(time,days);const url=URL.createObjectURL(new Blob([body],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download='pengingat-langkah-si-kecil.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
